! Create a dummy interface to hold our office network IP
interface lo
	ip address 192.168.10.1/24
!

! Define our identity
router bgp 100
	bgp router-id 1.1.1.1

	no bgp ebgp-requires-policy

	! Define our neighbor (Transit AS) and their ASN
	neighbor 10.100.30.3 remote-as 300

	! Define rogue neighbor
	neighbor 10.166.60.66 remote-as 666

	! Address family configuration (IPV4 Unicast)
	address-family ipv4 unicast
		neighbor 10.100.30.3 activate
		neighbor 10.166.60.66 activate

		! This is a dummy network we pretend to own
		network 192.168.10.0/24
	exit-address-family
!

! Static route so WireGuard UDP can reach Branch s WAN IP through Transit
ip route 10.200.30.0/24 10.100.30.3
!

log stdout
