router bgp 300
	bgp router-id 3.3.3.3

	no bgp ebgp-requires-policy
	
	! Define our neighbor (Main)
	neighbor 10.100.30.2 remote-as 100

	! Define second neighbor (Branch)
	neighbor 10.200.30.2 remote-as 200

	address-family ipv4 unicast
		neighbor 10.100.30.2 activate
		neighbor 10.200.30.2 activate

		! Share learnt routes
		! redistributes bgp
	exit-address-family
!
log stdout