router bgp 666
	bgp router-id 6.6.6.6

	no bgp ebgp-requires-policy

	! Define our neighbor (Transit AS) and their ASN
	neighbor 10.166.60.2 remote-as 100

	! Address family configuration (IPV4 Unicast)
	address-family ipv4 unicast
		neighbor 10.166.60.2 activate
	exit-address-family
!
log stdout
